[project]
name = "cj233cj-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pelican-neighbors>=1.2.0",
    "pelican-readtime>=0.2.1",
    "pelican-search>=1.1.0",
    "pelican[markdown]>=4.11.0.post0",
]
